version: '{build}'
image: Visual Studio 2017
skip_tags: true
build_script:
- ps: ./Build.ps1 
test: off
artifacts:
  - path: artifacts/Serilog.Sinks.Elasticsearch*.nupkg
  - path: artifacts/Serilog.Formatting.Elasticsearch*.nupkg
only_commits:
  files:
    - serilog-sinks-elasticsearch.sln
    - src/Serilog.Sinks.Elasticsearch/
    - src/Serilog.Formatting.Elasticsearch/
    - nuget.config
    - Build.ps1
    - assets/
    - test/Serilog.Sinks.Elasticsearch.Tests/
deploy:
- provider: NuGet
  api_key:
    secure: GltmkKBYpiHJZwgLgb98PTJfdCa4HFj9cbdZKAa1Zxcp/pJst9swF2/3XSdSjTZz
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: XSO0LDYd89yw5rAQ8HvAgdX7NBo1m4bEqHlj0NZxtA6zKunLwCSYoVHU+k3cvQIP
  on:
    branch: master
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
install:
  - choco install gitversion.portable -y
assembly_info:
  patch: false
before_build:
  - dotnet restore serilog-sinks-elasticsearch.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
